### ISSUE TITLE
Doors detected as walls when above 27ft when Wall-Height is used alongside Levels

### ISSUE THREAD

**Issue by SaintBalor** [theripper93/wall-height#20] opened 2022-09-08 17:02 UTC
**ALL OTHER MODULES DISABLED?** false
**Module:** Wall Height 4.7.1
**Conflicting Module (if applicable)**: Levels 3.1
**Foundry and System version**: eg. Foundry V10 - Build 284 / D&D5E 2.0.2
**OS, Hosting, Browser (if applicable)**: Noticed while Hosting - Replicated in OS for testing purposes
**Short Description of bug**: Doors are detected as walls when bottom height or token are 27ft or above, when Wall-Height is used alongside Levels. Players cannot open doors above those levels
**Simple steps to reproduce the bug**:
- Set both door bottom height and token at 26 - Result: Player is able to view and open door normally
- Set both door bottom height and token at 27 - Result: Player sees a wall instead of a door
- Set door bottom height to 26 and Token height to 27 - Result: Player sees a wall instead of a door.
- Set door bottom height at 27 and Token height to 26 - Result: Player sees a wall instead of a door. (this assumes the default token height of 5ft)

**Screenshots and/or console errors**:

Initial test setup (noticed the issue happening initially at 30 ft height)
![Test Setup](https://user-images.githubusercontent.com/42988763/189181295-9ff0db78-a321-4a06-ad67-59e5bb4af13e.png)

With both Levels and Wall Height (and dependencies) turned on:
![With Levels On](https://user-images.githubusercontent.com/42988763/189181620-c330d72e-3ce1-40d3-8335-12138e80d5a0.png)

Levels - On / wall Heights - Off:
![Wall Height Disabled](https://user-images.githubusercontent.com/42988763/189181744-43cbc126-c2ed-4288-ac5e-c317116014c4.png)

Levels - Off / Wall Heights - On:
![Without Levels on](https://user-images.githubusercontent.com/42988763/189181815-2e7dbd7f-b259-49a0-8f4d-f7ec62dd6d38.png)

Levels and Wall Heights - On / 26ft:
![26test2](https://user-images.githubusercontent.com/42988763/189181964-764d8bdd-b52c-4377-8324-f1fd112c0870.png)

Levels and Wall Heights - On / 27ft:
![27test2](https://user-images.githubusercontent.com/42988763/189182046-1586014f-5c8d-47ae-b789-592ff4886925.png)

**Comment by theripper93** [comment] 2022-09-08 22:58
This is a very weird issue, i don't see a reason for the height to matter, nor a reason for Levels altering the door behaviour (since there is no code for that). I suspect this is related to a core door bug, an update to foundry v10 is coming out soon, can you update me if that fixes the issue for you? As it stands i cannot reproduce this issue with the steps provided.

**Comment by SaintBalor** [comment] 2022-09-08 23:37
Huh, Interesting... Will do!
I'll also try other things like using a new world instead of a converted one to see if maybe that's a factor, but hopefully the update will fix that bug though. Thanks!

**Comment by SaintBalor** [comment] 2022-09-09 18:39
I've had a chance to test it in Foundry V10 - 285 to the same results
Here are the steps I took to reproduce the issue:

1. Performed clean installation of latest Foundry Version and installed 
2. Created new world "testworld"
3. Logged in as Gamemaster
4. Created new scenen - "testscene" with Fog of War exploration
5. Created new actor - "testactor" and enabled 30ft vision in Prototype Token
6. Enabled Levels, libWrapper and Wall Height modules
7. Placed "testactor" token on map inside testscene
8. Set testactor elevation to 27ft
9. Placed door in scene - set bottom height to 27/ set top height to 37
10. Clicked on token to view from its perspective

New pictures:
![newtest2](https://user-images.githubusercontent.com/42988763/189420155-0f7b3393-9d95-4425-9b68-7cbdbea0260c.png)

![newtest](https://user-images.githubusercontent.com/42988763/189420178-8cec359c-afb5-4c8c-afa0-2512a08aa9be.png)

Hopefully these revised steps help replicate the issue, but if you need it, I can zip the new world file I created. It has no assets, and only those three modules active.

**Comment by theripper93** [comment] 2022-09-09 21:59
Ok, with from scratch steps I might be able to repro

**Comment by theripper93** [comment] 2022-09-10 00:17
![image](https://user-images.githubusercontent.com/1346839/189460956-7b8e902a-681b-4ccd-9cc3-795659ae58b7.png)
![image](https://user-images.githubusercontent.com/1346839/189460963-0ffdad2d-ea58-4393-bb1e-251a1c393536.png)

Followed all the steps, cannot replicate the issue, at this point i'm really not sure what to do with this... beeing specific to 27 also makes no sense. Sorry but i'll close this issue for now, i have no clue what is going on, but i'll keep my eyes open if this arises again.

**Closed by theripper93** 2022-09-10 00:17 UTC
